version: '3.6'
services:
    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: server
        ports:
            - '3001:3001'
        restart: always
        env_file:
            - .env
        environment:
            - MONGO_URI=mongodb://mongoDB:27017/excelDB
        depends_on:
            - database

    database:
        image: mongo:latest
        container_name: mongoDB
        ports:
            - '27018:27017'
        volumes:
            - db_data:/data/db

    frontend:
        build:
            context: ../frontend # Assumes your React app is in a folder named 'frontend'
            dockerfile: Dockerfile
        container_name: frontend
        ports:
            - '3000:3000'
        environment:
            - VITE_API_URL=http://localhost:3001 # Pass backend URL as env var
        depends_on:
            - server # Ensure server is started first

volumes:
    db_data:
