name: Deploy

on:
    push:
        branches:
            - deploy-to-aws

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: duyhiep99/excel-backend:latest
                  build-args: |
                      NODE_ENV=${{ secrets.NODE_ENV }}
                      MONGO_URI=${{ secrets.MONGO_URI }}
                      SECRET_KEY=${{ secrets.SECRET_KEY }}
                      PORT=${{ secrets.PORT }}

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull Docker image from Docker Hub
              run: docker pull duyhiep99/excel-backend:latest

            - name: Stop and Remove Existing Docker Container
              run: |
                  docker stop excel-backend || true
                  docker rm excel-backend || true

            - name: Run Docker Container
              run: |
                  docker run -d \
                  -p 3001:3001 \
                  --name excel-backend \
                  -e NODE_ENV=${{ secrets.NODE_ENV }} \
                  -e MONGO_URI=${{ secrets.MONGO_URI }} \
                  -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
                  -e PORT=${{ secrets.PORT }} \
                  duyhiep99/excel-backend:latest
